# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - docs/**/*.*

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Debug'

steps:
- template: templates/use-dotnet.yml
- template: templates/dotnet-build.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
- template: templates/dotnet-test.yml
  parameters:
    buildConfiguration: $(buildConfiguration)
